## 1.1. Podstawowe struktury danych

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

### Ćwiczenie 1: Tworzenie jednowymiarowej tablicy
Stwórz jednowymiarową tablicę NumPy zawierającą liczby całkowite od 10 do 20 włącznie. Skorzystaj z funkcji
np.arange().

In [2]:
arr = np.arange(10,21)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20]


### Ćwiczenie 2: Tworzenie tablicy wielowymiarowej
Utwórz dwuwymiarową tablicę o wymiarach 3x4, wypełnioną liczbami zmiennoprzecinkowymi od 1.0 do 12.0.
Możesz użyć funkcji np.reshape().

In [7]:
arr = np.arange(1,13, dtype=float).reshape(3,4)
print(arr)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


### Ćwiczenie 3: Tablica zerowa
Stwórz dwuwymiarową tablicę 5x5 wypełnioną samymi zerami. Wykorzystaj funkcję np.zeros().

In [14]:
arr = np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Ćwiczenie 4: Tablica jednostkowa
Stwórz tablicę jednostkową (macierz jednostkową) o rozmiarze 4x4. Skorzystaj z funkcji np.eye().

In [21]:
arr = np.eye((4))
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Ćwiczenie 5: Tablica wypełniona stałą wartością
Utwórz tablicę jednowymiarową z pięcioma elementami, wypełnioną wartością 7. Użyj funkcji np.full().

In [24]:
arr = np.full(5,7)
print(arr)

[7 7 7 7 7]


### Ćwiczenie 6: Tworzenie tablicy z zakresu liczb
Stwórz tablicę NumPy zawierającą liczby z zakresu od 0 do 1 z krokiem 0.1. Skorzystaj z funkcji np.linspace().

In [31]:
arr = np.linspace(0, 1 ,11)
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Ćwiczenie 7: Losowa tablica
Wygeneruj dwuwymiarową tablicę o wymiarach 10x10, wypełnioną losowymi liczbami zmiennoprzecinkowymi z
zakresu od 0 do 1. Skorzystaj z funkcji np.random.random().

In [46]:
arr = np.random.random((10,10))
print(arr)

[[0.8313823  0.54443505 0.04734336 0.26614442 0.78289944 0.88500501
  0.35161339 0.96571668 0.98917269 0.14678887]
 [0.72046988 0.53581194 0.33515576 0.95539428 0.90571999 0.20298515
  0.01575665 0.20512353 0.46610601 0.25833633]
 [0.95885815 0.70838431 0.12757743 0.95957558 0.88165156 0.9743313
  0.94815492 0.13685474 0.88494842 0.0988526 ]
 [0.1013459  0.68334823 0.36211927 0.41535209 0.42919398 0.28039127
  0.5536312  0.37171    0.60150452 0.56594372]
 [0.12155671 0.5786115  0.14398863 0.58132945 0.21069929 0.83813744
  0.26655941 0.67107019 0.90497505 0.61397354]
 [0.77939064 0.31726959 0.59790655 0.12135986 0.88124199 0.04972112
  0.01687789 0.65231644 0.21006546 0.89397034]
 [0.55375653 0.66366797 0.57435448 0.59429174 0.42654926 0.08942588
  0.60061432 0.11363088 0.88339    0.40086747]
 [0.40461144 0.9862472  0.33714713 0.29044049 0.59664613 0.13608377
  0.01321889 0.82322617 0.01661618 0.92425897]
 [0.17072916 0.23256145 0.11746266 0.67328275 0.5331437  0.39055432
  0.81248853 

### Ćwiczenie 8: Tablica z losowymi liczbami całkowitymi
Utwórz tablicę 6x6 wypełnioną losowymi liczbami całkowitymi z przedziału od 0 do 100. Użyj funkcji
np.random.randint().

In [55]:
arr = np.random.randint(0,101,(6,6))
print(arr)

[[86 66 68 85 10 67]
 [72 93 37 70 25 67]
 [66 49 85 76 22 38]
 [21  3 79 26 82 31]
 [25 92 64 62 39 33]
 [32 84 49 66 78 13]]


### Ćwiczenie 9: Tablica z wartością początkową, krokiem i wymiarem
Stwórz tablicę jednowymiarową z wartościami zaczynającymi się od 5, z krokiem 2, o długości 10 elementów. Użyj
funkcji np.arange().

In [62]:
arr = np.arange(5,25,2)
print(arr)

[ 5  7  9 11 13 15 17 19 21 23]


### Ćwiczenie 10: Zmienianie kształtu tablicy
Stwórz jednowymiarową tablicę zawierającą liczby od 1 do 16, a następnie przekształć ją w tablicę o wymiarach
4x4. Użyj funkcji np.reshape().

In [67]:
arr = np.arange(1,17).reshape(4,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### Ćwiczenie 11: Tworzenie tablicy z określonym typem danych
Stwórz jednowymiarową tablicę NumPy zawierającą liczby całkowite od 1 do 10, ale upewnij się, że typ danych tablicy to float64.

In [83]:
arr = np.arange(1,11,dtype=np.float64)
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


### Ćwiczenie 12: Zmiana typu danych istniejącej tablicy
Utwórz tablicę NumPy z liczbami całkowitymi od 10 do 20, a następnie zmień typ danych tej tablicy na int16.

In [89]:
arr = np.arange(10,21,dtype=np.float32).astype(np.int16)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20]


### Ćwiczenie 13: Tworzenie tablicy z wartościami zmiennoprzecinkowymi
Stwórz dwuwymiarową tablicę NumPy o wymiarach 4x4 wypełnioną losowymi wartościami zmiennoprzecinko
wymi z zakresu od 0 do 1, z typem danych float32

In [108]:
arr = np.random.random((4,4)).astype(np.float32)
print(arr)

[[0.13577408 0.4903139  0.4724693  0.9215464 ]
 [0.4187673  0.15902935 0.27364597 0.3821887 ]
 [0.35826197 0.24577077 0.8810874  0.41435784]
 [0.63716495 0.47177032 0.21950085 0.18080735]]


### Ćwiczenie 14: Sprawdzenie typu danych tablicy
Utwórz tablicę NumPy zawierającą liczby od 1 do 5, a następnie sprawdź i wyświetl typ danych tej tablicy.

In [119]:
arr = np.arange(1,6)
arr.dtype

dtype('int64')

### Ćwiczenie 15: Tworzenie tablicy logicznej
Stwórz tablicę NumPy o wymiarach 3x3 wypełnioną wartościami logicznymi (True i False), używając typu danych
bool.

In [124]:
bool_values = np.array([[True, False, True],
[False, True, False],
[True, False, True]], dtype=bool)

## 1.2. Proste indeksowanie i wycinanie tablic

### Ćwiczenie 16: Wyciąganie elementów z tablicy jednowymiarowej
Utwórz jednowymiarową tablicę NumPy zawierającą liczby od 0 do 20. Wyciągnij elementy o indeksach 3, 5 i 7.

In [132]:
arr = np.arange(21)
indexes = [3, 5, 7]
print(arr[indexes])


[3 5 7]


### Ćwiczenie 17: Wycinanie fragmentu tablicy dwuwymiarowej
Stwórz dwuwymiarową tablicę o wymiarach 4x4, zawierającą liczby od 1 do 16. Wytnij i wyświetl podtablicę
składającą się z wierszy 1 i 2 oraz kolumn 2 i 3.

In [177]:
arr = np.arange(1,17).reshape(4,4)
sub_arr = arr[1:3, 2:4]
# print("Oryginal: ",arr)
# print("Sliced: ",sub_arr)
print(pd.DataFrame(arr))
print("------")
print(pd.DataFrame(sub_arr))



    0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
------
    0   1
0   7   8
1  11  12


### Ćwiczenie 18: Wybieranie elementów wiersza
Utwórz dwuwymiarową tablicę 5x5 z liczbami od 0 do 24. Wybierz i wyświetl wszystkie elementy w trzecim wierszu.

In [188]:
arr = np.arange(25).reshape(5,5)
print(arr)
print(arr[2,:])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[10 11 12 13 14]


### Ćwiczenie 19: Indeksowanie z użyciem zakresu
Stwórz tablicę NumPy z liczbami od 10 do 100 z krokiem 10. Wyciągnij co drugi element tej tablicy, zaczynając od
drugiego elementu.

In [195]:
arr = np.arange(10,101,10)
print(arr[1::2])

[ 20  40  60  80 100]


### Ćwiczenie 20: Wycinanie tablicy wielowymiarowej
Utwórz trójwymiarową tablicę o wymiarach 4x4x3, wypełnioną losowymi wartościami całkowitymi. Wyciągnij
drugą warstwę (trzeci wymiar) tej tablicy.

In [226]:
arr = np.random.randint(0,10,size=(4,4,3))
print(arr[::1])

[[[7 5 3]
  [7 2 4]
  [3 5 4]
  [6 0 3]]

 [[6 6 0]
  [2 4 5]
  [0 6 6]
  [6 1 0]]

 [[8 5 4]
  [1 8 9]
  [1 8 8]
  [2 2 9]]

 [[3 6 2]
  [1 8 7]
  [3 9 7]
  [9 6 9]]]


### Ćwiczenie 21: Odwrócenie kolejności elementów
Utwórz tablicę jednowymiarową z liczbami od 1 do 10, a następnie odwróć kolejność elementów w tablicy. Możesz
użyć funkcji flip().

In [237]:
arr = np.arange(1,11)
print(np.flip(arr))

[10  9  8  7  6  5  4  3  2  1]


### Ćwiczenie 22: Modyfikacja fragmentu tablicy
Stwórz dwuwymiarową tablicę 5x5, wypełnioną liczbami od 1 do 25. Zastąp elementy w wierszu 2 i kolumnie 3
wartościami 99.

In [15]:
arr = np.random.randint(1,26,size=(5,5))
print(arr)
arr[1,:]=99 
arr[:,2]= 99
print(arr)


[[ 4  3 14  8 20]
 [10 21 24 14 22]
 [ 2  6 13  5 21]
 [ 5 19 24 21 13]
 [ 1 19 13 11 11]]
[[ 4  3 99  8 20]
 [99 99 99 99 99]
 [ 2  6 99  5 21]
 [ 5 19 99 21 13]
 [ 1 19 99 11 11]]


### Ćwiczenie 23: Indeksowanie z warunkiem logicznym
Utwórz tablicę NumPy z liczbami od 1 do 20. Wyciągnij z niej wszystkie liczby parzyste.

In [24]:
arr = np.arange(1,21)
print(arr)
arr = arr[arr % 2 == 0]
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]


### Ćwiczenie 24: Wyciąganie elementów z użyciem listy indeksów
Stwórz jednowymiarową tablicę zawierającą liczby od 0 do 10. Wyciągnij elementy o indeksach podanych w liście
[1, 3, 5, 7, 9].

In [29]:
arr = np.arange(11)
print(arr)
arr = arr[[1, 3, 5, 7, 9]]
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


### Ćwiczenie 25: Wycinanie tablicy z krokiem
Utwórz tablicę jednowymiarową z liczbami od 1 do 30. Wyciągnij co trzeci element tablicy, zaczynając od piątego
elementu.

In [42]:
arr = np.arange(1,31)
print(arr)
res = arr[4::3]
print(res)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
[ 5  8 11 14 17 20 23 26 29]


## 1.3. Podstawowe operacje na danych w tablicach

In [47]:
tab_1 = np.array([1, 2, 3, 4, 5, 6])
tab_2 = np.array([5, 6, 7, 8, 9, 10])
tab_3 = np.arange(1, 21)
tab_4 = np.array([[i] for i in range(2, 13, 2)])

### Ćwiczenie 26: Operacje arytmetyczne I
1. Wykonaj operację dodawania na tablicach tab_1 i tab_2.
2. Pomnóż każdy element tablicy tab_1 przez 3.
3. Oblicz iloczyn elementów tab_4 z liczbą 0.5.
4. Podziel elementy tab_2 przez odpowiadające im elementy tab_1.
5. Do każdego elementu tab_3 dodaj wektor [10, 20, 30, 40, 50].
6. Wykonaj dzielenie modulo tab_2 przez tab_1.
7. Pomnóż macierz tab_4 przez wektor [1, 2, 3].
8. Podnieś elementy tab_1 do kwadratu i podziel przez 2.
9. Wykonaj operację dzielenia całkowitego tab_3 przez 3.
10. Pomnóż tab_4 przez transponowaną wersję samej siebie.

In [54]:
add = tab_1 + tab_2
print(add)

[ 6  8 10 12 14 16]


In [56]:
multiply = tab_1 * tab_2
print(multiply)

[ 5 12 21 32 45 60]


In [58]:
res = tab_4 * 0.5
print(res)

[[1.]
 [2.]
 [3.]
 [4.]
 [5.]
 [6.]]


In [60]:
res4 = tab_2 / tab_1
print(res1)

[5.         3.         2.33333333 2.         1.8        1.66666667]


In [66]:
res5 = tab_3.reshape(4,5) + np.array([10, 20, 30, 40 ,50])

In [68]:
res6 = np.mod(tab_2, tab_1)
print(res6)

[0 0 1 0 4 4]


In [70]:
res7 = tab_4 * np.array([1, 2, 3])

In [72]:
res8  = (tab_1 ** 2) / 2

In [ ]:
res9 = tab_3 // 3

In [74]:
res10 = tab_4 @ tab_4.T
print(res10)

[[  4   8  12  16  20  24]
 [  8  16  24  32  40  48]
 [ 12  24  36  48  60  72]
 [ 16  32  48  64  80  96]
 [ 20  40  60  80 100 120]
 [ 24  48  72  96 120 144]]


## Funkcje uniwersalne

### Ćwiczenie 27: np.sqrt() i np.square()
Utwórz tablicę zawierającą 10 losowych liczb całkowitych z zakresu 1 99, a następnie wykorzystaj odpowiednią
funkcję do obliczenia:
• pierwiastka kwadratowego każdej liczby,
• kwadratu każdej liczby.

In [88]:
arr = np.random.randint(1,100,size=(10))
sqr= np.sqrt(arr)
square = np.square(arr)

### Ćwiczenie 28: np.abs()
Oblicz bezwzględne różnice wartości w podanych tablicach:

In [91]:
import random
tab_1 = [i + random.random() for i in range(10)]
tab_2 = [i + random.random() for i in range(1,11)]

In [95]:
res = np.abs(np.array(tab_1) - np.array(tab_2))

### Ćwiczenie 30: np.max() kontra np.maximum()
Dane są dwie tablice:

In [104]:
tab_1 = np.random.randint(1, 21, 10)
tab_2 = np.random.randint(1, 11, 10)
print(tab_1)
print(tab_2)
print("wynik działania funkcji max:")
print(np.max(tab_1))
print(np.max(tab_2))
print("Wynik działania funkcji maximum:")
print(np.maximum(tab_1, tab_2))

[17  3  9 14 17  5  8  6 15  5]
[3 9 4 8 9 5 6 1 1 7]
wynik działania funkcji max:
17
9
Wynik działania funkcji maximum:
[17  9  9 14 17  5  8  6 15  7]


### Ćwiczenie 31: Funkcje trygonometryczne
Utwórz tablicę zawierającą kąty w radianach [π/6, π/4, π/3, π/2, π]. Wykorzystaj funkcje trygonometryczne
do:
• obliczenia sinusa, cosinusa i tangensa każdego kąta,
• sprawdzenia tożsamości trygonometrycznej sin²(x) + cos²(x) = 1,
• znalezienia kątów, dla których cos(x) > sin(x).

In [111]:
kat = np.pi / np.arange(6, 0, -1)
sin = np.sin(kat)