## 1.1. Podstawowe struktury danych

In [3]:
import numpy as np

### Ćwiczenie 1: Tworzenie jednowymiarowej tablicy
Stwórz jednowymiarową tablicę NumPy zawierającą liczby całkowite od 10 do 20 włącznie. Skorzystaj z funkcji
np.arange().

In [2]:
arr = np.arange(10,21)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20]


### Ćwiczenie 2: Tworzenie tablicy wielowymiarowej
Utwórz dwuwymiarową tablicę o wymiarach 3x4, wypełnioną liczbami zmiennoprzecinkowymi od 1.0 do 12.0.
Możesz użyć funkcji np.reshape().

In [7]:
arr = np.arange(1,13, dtype=float).reshape(3,4)
print(arr)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


### Ćwiczenie 3: Tablica zerowa
Stwórz dwuwymiarową tablicę 5x5 wypełnioną samymi zerami. Wykorzystaj funkcję np.zeros().

In [14]:
arr = np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Ćwiczenie 4: Tablica jednostkowa
Stwórz tablicę jednostkową (macierz jednostkową) o rozmiarze 4x4. Skorzystaj z funkcji np.eye().

In [21]:
arr = np.eye((4))
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Ćwiczenie 5: Tablica wypełniona stałą wartością
Utwórz tablicę jednowymiarową z pięcioma elementami, wypełnioną wartością 7. Użyj funkcji np.full().

In [24]:
arr = np.full(5,7)
print(arr)

[7 7 7 7 7]


### Ćwiczenie 6: Tworzenie tablicy z zakresu liczb
Stwórz tablicę NumPy zawierającą liczby z zakresu od 0 do 1 z krokiem 0.1. Skorzystaj z funkcji np.linspace().

In [31]:
arr = np.linspace(0, 1 ,11)
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Ćwiczenie 7: Losowa tablica
Wygeneruj dwuwymiarową tablicę o wymiarach 10x10, wypełnioną losowymi liczbami zmiennoprzecinkowymi z
zakresu od 0 do 1. Skorzystaj z funkcji np.random.random().

In [46]:
arr = np.random.random((10,10))
print(arr)

[[0.8313823  0.54443505 0.04734336 0.26614442 0.78289944 0.88500501
  0.35161339 0.96571668 0.98917269 0.14678887]
 [0.72046988 0.53581194 0.33515576 0.95539428 0.90571999 0.20298515
  0.01575665 0.20512353 0.46610601 0.25833633]
 [0.95885815 0.70838431 0.12757743 0.95957558 0.88165156 0.9743313
  0.94815492 0.13685474 0.88494842 0.0988526 ]
 [0.1013459  0.68334823 0.36211927 0.41535209 0.42919398 0.28039127
  0.5536312  0.37171    0.60150452 0.56594372]
 [0.12155671 0.5786115  0.14398863 0.58132945 0.21069929 0.83813744
  0.26655941 0.67107019 0.90497505 0.61397354]
 [0.77939064 0.31726959 0.59790655 0.12135986 0.88124199 0.04972112
  0.01687789 0.65231644 0.21006546 0.89397034]
 [0.55375653 0.66366797 0.57435448 0.59429174 0.42654926 0.08942588
  0.60061432 0.11363088 0.88339    0.40086747]
 [0.40461144 0.9862472  0.33714713 0.29044049 0.59664613 0.13608377
  0.01321889 0.82322617 0.01661618 0.92425897]
 [0.17072916 0.23256145 0.11746266 0.67328275 0.5331437  0.39055432
  0.81248853 

### Ćwiczenie 8: Tablica z losowymi liczbami całkowitymi
Utwórz tablicę 6x6 wypełnioną losowymi liczbami całkowitymi z przedziału od 0 do 100. Użyj funkcji
np.random.randint().

In [55]:
arr = np.random.randint(0,101,(6,6))
print(arr)

[[86 66 68 85 10 67]
 [72 93 37 70 25 67]
 [66 49 85 76 22 38]
 [21  3 79 26 82 31]
 [25 92 64 62 39 33]
 [32 84 49 66 78 13]]


### Ćwiczenie 9: Tablica z wartością początkową, krokiem i wymiarem
Stwórz tablicę jednowymiarową z wartościami zaczynającymi się od 5, z krokiem 2, o długości 10 elementów. Użyj
funkcji np.arange().

In [62]:
arr = np.arange(5,25,2)
print(arr)

[ 5  7  9 11 13 15 17 19 21 23]


### Ćwiczenie 10: Zmienianie kształtu tablicy
Stwórz jednowymiarową tablicę zawierającą liczby od 1 do 16, a następnie przekształć ją w tablicę o wymiarach
4x4. Użyj funkcji np.reshape().

In [67]:
arr = np.arange(1,17).reshape(4,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### Ćwiczenie 11: Tworzenie tablicy z określonym typem danych
Stwórz jednowymiarową tablicę NumPy zawierającą liczby całkowite od 1 do 10, ale upewnij się, że typ danych tablicy to float64.

In [83]:
arr = np.arange(1,11,dtype=np.float64)
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


### Ćwiczenie 12: Zmiana typu danych istniejącej tablicy
Utwórz tablicę NumPy z liczbami całkowitymi od 10 do 20, a następnie zmień typ danych tej tablicy na int16.

In [89]:
arr = np.arange(10,21,dtype=np.float32).astype(np.int16)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20]


### Ćwiczenie 13: Tworzenie tablicy z wartościami zmiennoprzecinkowymi
Stwórz dwuwymiarową tablicę NumPy o wymiarach 4x4 wypełnioną losowymi wartościami zmiennoprzecinko
wymi z zakresu od 0 do 1, z typem danych float32

In [108]:
arr = np.random.random((4,4)).astype(np.float32)
print(arr)

[[0.13577408 0.4903139  0.4724693  0.9215464 ]
 [0.4187673  0.15902935 0.27364597 0.3821887 ]
 [0.35826197 0.24577077 0.8810874  0.41435784]
 [0.63716495 0.47177032 0.21950085 0.18080735]]


### Ćwiczenie 14: Sprawdzenie typu danych tablicy
Utwórz tablicę NumPy zawierającą liczby od 1 do 5, a następnie sprawdź i wyświetl typ danych tej tablicy.

In [119]:
arr = np.arange(1,6)
arr.dtype

dtype('int64')

### Ćwiczenie 15: Tworzenie tablicy logicznej
Stwórz tablicę NumPy o wymiarach 3x3 wypełnioną wartościami logicznymi (True i False), używając typu danych
bool.

In [122]:
logiczna = np.array([[True, False, True],
[False, True, False],
[True, False, True]], dtype=bool)