## 1.1. Podstawowe struktury danych

In [69]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

### Ćwiczenie 1: Tworzenie jednowymiarowej tablicy
Stwórz jednowymiarową tablicę NumPy zawierającą liczby całkowite od 10 do 20 włącznie. Skorzystaj z funkcji
np.arange().

In [2]:
arr = np.arange(10,21)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20]


### Ćwiczenie 2: Tworzenie tablicy wielowymiarowej
Utwórz dwuwymiarową tablicę o wymiarach 3x4, wypełnioną liczbami zmiennoprzecinkowymi od 1.0 do 12.0.
Możesz użyć funkcji np.reshape().

In [7]:
arr = np.arange(1,13, dtype=float).reshape(3,4)
print(arr)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


### Ćwiczenie 3: Tablica zerowa
Stwórz dwuwymiarową tablicę 5x5 wypełnioną samymi zerami. Wykorzystaj funkcję np.zeros().

In [14]:
arr = np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Ćwiczenie 4: Tablica jednostkowa
Stwórz tablicę jednostkową (macierz jednostkową) o rozmiarze 4x4. Skorzystaj z funkcji np.eye().

In [21]:
arr = np.eye((4))
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Ćwiczenie 5: Tablica wypełniona stałą wartością
Utwórz tablicę jednowymiarową z pięcioma elementami, wypełnioną wartością 7. Użyj funkcji np.full().

In [24]:
arr = np.full(5,7)
print(arr)

[7 7 7 7 7]


### Ćwiczenie 6: Tworzenie tablicy z zakresu liczb
Stwórz tablicę NumPy zawierającą liczby z zakresu od 0 do 1 z krokiem 0.1. Skorzystaj z funkcji np.linspace().

In [31]:
arr = np.linspace(0, 1 ,11)
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Ćwiczenie 7: Losowa tablica
Wygeneruj dwuwymiarową tablicę o wymiarach 10x10, wypełnioną losowymi liczbami zmiennoprzecinkowymi z
zakresu od 0 do 1. Skorzystaj z funkcji np.random.random().

In [46]:
arr = np.random.random((10,10))
print(arr)

[[0.8313823  0.54443505 0.04734336 0.26614442 0.78289944 0.88500501
  0.35161339 0.96571668 0.98917269 0.14678887]
 [0.72046988 0.53581194 0.33515576 0.95539428 0.90571999 0.20298515
  0.01575665 0.20512353 0.46610601 0.25833633]
 [0.95885815 0.70838431 0.12757743 0.95957558 0.88165156 0.9743313
  0.94815492 0.13685474 0.88494842 0.0988526 ]
 [0.1013459  0.68334823 0.36211927 0.41535209 0.42919398 0.28039127
  0.5536312  0.37171    0.60150452 0.56594372]
 [0.12155671 0.5786115  0.14398863 0.58132945 0.21069929 0.83813744
  0.26655941 0.67107019 0.90497505 0.61397354]
 [0.77939064 0.31726959 0.59790655 0.12135986 0.88124199 0.04972112
  0.01687789 0.65231644 0.21006546 0.89397034]
 [0.55375653 0.66366797 0.57435448 0.59429174 0.42654926 0.08942588
  0.60061432 0.11363088 0.88339    0.40086747]
 [0.40461144 0.9862472  0.33714713 0.29044049 0.59664613 0.13608377
  0.01321889 0.82322617 0.01661618 0.92425897]
 [0.17072916 0.23256145 0.11746266 0.67328275 0.5331437  0.39055432
  0.81248853 

### Ćwiczenie 8: Tablica z losowymi liczbami całkowitymi
Utwórz tablicę 6x6 wypełnioną losowymi liczbami całkowitymi z przedziału od 0 do 100. Użyj funkcji
np.random.randint().

In [55]:
arr = np.random.randint(0,101,(6,6))
print(arr)

[[86 66 68 85 10 67]
 [72 93 37 70 25 67]
 [66 49 85 76 22 38]
 [21  3 79 26 82 31]
 [25 92 64 62 39 33]
 [32 84 49 66 78 13]]


### Ćwiczenie 9: Tablica z wartością początkową, krokiem i wymiarem
Stwórz tablicę jednowymiarową z wartościami zaczynającymi się od 5, z krokiem 2, o długości 10 elementów. Użyj
funkcji np.arange().

In [62]:
arr = np.arange(5,25,2)
print(arr)

[ 5  7  9 11 13 15 17 19 21 23]


### Ćwiczenie 10: Zmienianie kształtu tablicy
Stwórz jednowymiarową tablicę zawierającą liczby od 1 do 16, a następnie przekształć ją w tablicę o wymiarach
4x4. Użyj funkcji np.reshape().

In [67]:
arr = np.arange(1,17).reshape(4,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### Ćwiczenie 11: Tworzenie tablicy z określonym typem danych
Stwórz jednowymiarową tablicę NumPy zawierającą liczby całkowite od 1 do 10, ale upewnij się, że typ danych tablicy to float64.

In [83]:
arr = np.arange(1,11,dtype=np.float64)
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


### Ćwiczenie 12: Zmiana typu danych istniejącej tablicy
Utwórz tablicę NumPy z liczbami całkowitymi od 10 do 20, a następnie zmień typ danych tej tablicy na int16.

In [89]:
arr = np.arange(10,21,dtype=np.float32).astype(np.int16)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20]


### Ćwiczenie 13: Tworzenie tablicy z wartościami zmiennoprzecinkowymi
Stwórz dwuwymiarową tablicę NumPy o wymiarach 4x4 wypełnioną losowymi wartościami zmiennoprzecinko
wymi z zakresu od 0 do 1, z typem danych float32

In [108]:
arr = np.random.random((4,4)).astype(np.float32)
print(arr)

[[0.13577408 0.4903139  0.4724693  0.9215464 ]
 [0.4187673  0.15902935 0.27364597 0.3821887 ]
 [0.35826197 0.24577077 0.8810874  0.41435784]
 [0.63716495 0.47177032 0.21950085 0.18080735]]


### Ćwiczenie 14: Sprawdzenie typu danych tablicy
Utwórz tablicę NumPy zawierającą liczby od 1 do 5, a następnie sprawdź i wyświetl typ danych tej tablicy.

In [119]:
arr = np.arange(1,6)
arr.dtype

dtype('int64')

### Ćwiczenie 15: Tworzenie tablicy logicznej
Stwórz tablicę NumPy o wymiarach 3x3 wypełnioną wartościami logicznymi (True i False), używając typu danych
bool.

In [124]:
bool_values = np.array([[True, False, True],
[False, True, False],
[True, False, True]], dtype=bool)

## 1.2. Proste indeksowanie i wycinanie tablic

### Ćwiczenie 16: Wyciąganie elementów z tablicy jednowymiarowej
Utwórz jednowymiarową tablicę NumPy zawierającą liczby od 0 do 20. Wyciągnij elementy o indeksach 3, 5 i 7.

In [132]:
arr = np.arange(21)
indexes = [3, 5, 7]
print(arr[indexes])


[3 5 7]


### Ćwiczenie 17: Wycinanie fragmentu tablicy dwuwymiarowej
Stwórz dwuwymiarową tablicę o wymiarach 4x4, zawierającą liczby od 1 do 16. Wytnij i wyświetl podtablicę
składającą się z wierszy 1 i 2 oraz kolumn 2 i 3.

In [177]:
arr = np.arange(1,17).reshape(4,4)
sub_arr = arr[1:3, 2:4]
# print("Oryginal: ",arr)
# print("Sliced: ",sub_arr)
print(pd.DataFrame(arr))
print("------")
print(pd.DataFrame(sub_arr))



    0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
------
    0   1
0   7   8
1  11  12


### Ćwiczenie 18: Wybieranie elementów wiersza
Utwórz dwuwymiarową tablicę 5x5 z liczbami od 0 do 24. Wybierz i wyświetl wszystkie elementy w trzecim wierszu.

In [188]:
arr = np.arange(25).reshape(5,5)
print(arr)
print(arr[2,:])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[10 11 12 13 14]


### Ćwiczenie 19: Indeksowanie z użyciem zakresu
Stwórz tablicę NumPy z liczbami od 10 do 100 z krokiem 10. Wyciągnij co drugi element tej tablicy, zaczynając od
drugiego elementu.

In [195]:
arr = np.arange(10,101,10)
print(arr[1::2])

[ 20  40  60  80 100]


### Ćwiczenie 20: Wycinanie tablicy wielowymiarowej
Utwórz trójwymiarową tablicę o wymiarach 4x4x3, wypełnioną losowymi wartościami całkowitymi. Wyciągnij
drugą warstwę (trzeci wymiar) tej tablicy.

In [226]:
arr = np.random.randint(0,10,size=(4,4,3))
print(arr[::1])

[[[7 5 3]
  [7 2 4]
  [3 5 4]
  [6 0 3]]

 [[6 6 0]
  [2 4 5]
  [0 6 6]
  [6 1 0]]

 [[8 5 4]
  [1 8 9]
  [1 8 8]
  [2 2 9]]

 [[3 6 2]
  [1 8 7]
  [3 9 7]
  [9 6 9]]]


### Ćwiczenie 21: Odwrócenie kolejności elementów
Utwórz tablicę jednowymiarową z liczbami od 1 do 10, a następnie odwróć kolejność elementów w tablicy. Możesz
użyć funkcji flip().

In [237]:
arr = np.arange(1,11)
print(np.flip(arr))

[10  9  8  7  6  5  4  3  2  1]


### Ćwiczenie 22: Modyfikacja fragmentu tablicy
Stwórz dwuwymiarową tablicę 5x5, wypełnioną liczbami od 1 do 25. Zastąp elementy w wierszu 2 i kolumnie 3
wartościami 99.

In [15]:
arr = np.random.randint(1,26,size=(5,5))
print(arr)
arr[1,:]=99 
arr[:,2]= 99
print(arr)


[[ 4  3 14  8 20]
 [10 21 24 14 22]
 [ 2  6 13  5 21]
 [ 5 19 24 21 13]
 [ 1 19 13 11 11]]
[[ 4  3 99  8 20]
 [99 99 99 99 99]
 [ 2  6 99  5 21]
 [ 5 19 99 21 13]
 [ 1 19 99 11 11]]


### Ćwiczenie 23: Indeksowanie z warunkiem logicznym
Utwórz tablicę NumPy z liczbami od 1 do 20. Wyciągnij z niej wszystkie liczby parzyste.

In [24]:
arr = np.arange(1,21)
print(arr)
arr = arr[arr % 2 == 0]
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]


### Ćwiczenie 24: Wyciąganie elementów z użyciem listy indeksów
Stwórz jednowymiarową tablicę zawierającą liczby od 0 do 10. Wyciągnij elementy o indeksach podanych w liście
[1, 3, 5, 7, 9].

In [29]:
arr = np.arange(11)
print(arr)
arr = arr[[1, 3, 5, 7, 9]]
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


### Ćwiczenie 25: Wycinanie tablicy z krokiem
Utwórz tablicę jednowymiarową z liczbami od 1 do 30. Wyciągnij co trzeci element tablicy, zaczynając od piątego
elementu.

In [42]:
arr = np.arange(1,31)
print(arr)
res = arr[4::3]
print(res)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
[ 5  8 11 14 17 20 23 26 29]


## 1.3. Podstawowe operacje na danych w tablicach

In [47]:
tab_1 = np.array([1, 2, 3, 4, 5, 6])
tab_2 = np.array([5, 6, 7, 8, 9, 10])
tab_3 = np.arange(1, 21)
tab_4 = np.array([[i] for i in range(2, 13, 2)])

### Ćwiczenie 26: Operacje arytmetyczne I
1. Wykonaj operację dodawania na tablicach tab_1 i tab_2.
2. Pomnóż każdy element tablicy tab_1 przez 3.
3. Oblicz iloczyn elementów tab_4 z liczbą 0.5.
4. Podziel elementy tab_2 przez odpowiadające im elementy tab_1.
5. Do każdego elementu tab_3 dodaj wektor [10, 20, 30, 40, 50].
6. Wykonaj dzielenie modulo tab_2 przez tab_1.
7. Pomnóż macierz tab_4 przez wektor [1, 2, 3].
8. Podnieś elementy tab_1 do kwadratu i podziel przez 2.
9. Wykonaj operację dzielenia całkowitego tab_3 przez 3.
10. Pomnóż tab_4 przez transponowaną wersję samej siebie.

In [54]:
add = tab_1 + tab_2
print(add)

[ 6  8 10 12 14 16]


In [56]:
multiply = tab_1 * tab_2
print(multiply)

[ 5 12 21 32 45 60]


In [58]:
res = tab_4 * 0.5
print(res)

[[1.]
 [2.]
 [3.]
 [4.]
 [5.]
 [6.]]


In [60]:
res4 = tab_2 / tab_1
print(res1)

[5.         3.         2.33333333 2.         1.8        1.66666667]


In [66]:
res5 = tab_3.reshape(4,5) + np.array([10, 20, 30, 40 ,50])

In [68]:
res6 = np.mod(tab_2, tab_1)
print(res6)

[0 0 1 0 4 4]


In [70]:
res7 = tab_4 * np.array([1, 2, 3])

In [72]:
res8  = (tab_1 ** 2) / 2

In [ ]:
res9 = tab_3 // 3

In [74]:
res10 = tab_4 @ tab_4.T
print(res10)

[[  4   8  12  16  20  24]
 [  8  16  24  32  40  48]
 [ 12  24  36  48  60  72]
 [ 16  32  48  64  80  96]
 [ 20  40  60  80 100 120]
 [ 24  48  72  96 120 144]]


## Funkcje uniwersalne

### Ćwiczenie 27: np.sqrt() i np.square()
Utwórz tablicę zawierającą 10 losowych liczb całkowitych z zakresu 1 99, a następnie wykorzystaj odpowiednią
funkcję do obliczenia:
• pierwiastka kwadratowego każdej liczby,
• kwadratu każdej liczby.

In [88]:
arr = np.random.randint(1,100,size=(10))
sqr= np.sqrt(arr)
square = np.square(arr)

### Ćwiczenie 28: np.abs()
Oblicz bezwzględne różnice wartości w podanych tablicach:

In [91]:
import random
tab_1 = [i + random.random() for i in range(10)]
tab_2 = [i + random.random() for i in range(1,11)]

In [95]:
res = np.abs(np.array(tab_1) - np.array(tab_2))

### Ćwiczenie 30: np.max() kontra np.maximum()
Dane są dwie tablice:

In [104]:
tab_1 = np.random.randint(1, 21, 10)
tab_2 = np.random.randint(1, 11, 10)
print(tab_1)
print(tab_2)
print("wynik działania funkcji max:")
print(np.max(tab_1))
print(np.max(tab_2))
print("Wynik działania funkcji maximum:")
print(np.maximum(tab_1, tab_2))

[17  3  9 14 17  5  8  6 15  5]
[3 9 4 8 9 5 6 1 1 7]
wynik działania funkcji max:
17
9
Wynik działania funkcji maximum:
[17  9  9 14 17  5  8  6 15  7]


### Ćwiczenie 31: Funkcje trygonometryczne
Utwórz tablicę zawierającą kąty w radianach [π/6, π/4, π/3, π/2, π]. Wykorzystaj funkcje trygonometryczne
do:
• obliczenia sinusa, cosinusa i tangensa każdego kąta,
• sprawdzenia tożsamości trygonometrycznej sin²(x) + cos²(x) = 1,
• znalezienia kątów, dla których cos(x) > sin(x).

In [113]:
kat = np.pi / np.arange(6, 0, -1)
sin = np.sin(kat)
print(sin)

[5.00000000e-01 5.87785252e-01 7.07106781e-01 8.66025404e-01
 1.00000000e+00 1.22464680e-16]


## 1.5 Broadcasting

### Cwiczenie 32: Konwersja temperatur
Dokonaj konwersji tabeli temperatur ze skali Celsjusza do skali Fahrenheita.

In [122]:
temp_c = np.array([
[20, 22, 21], # Miasto 1
[18, 19, 20], # Miasto 2
[23, 24, 22], # Miasto 3
[17, 18, 19], # Miasto 4
[21, 20, 20] # Miasto 5
])
temp_fa = 1.8 * temp_c + 32

### Ćwiczenie 33: Normalizacja danych
Oblicz wynik procentowy na podstawie informacji o punktach uzyskanych przez uczniów z testów oraz maksy
malnej licznie punktów do uzyskania z każdego testu.

In [125]:
wyniki_uczniów = np.array([
[85, 92, 78], # Uczeń 1 (matematyka, fizyka, chemia)
[95, 88, 65], # Uczeń 2
[78, 85, 80] # Uczeń 3
])
punkty_max = np.array([100, 120, 80])

### Ćwiczenie 34: Ceny w sklepie
Oblicz końcowe ceny produktów w poszczególnych dniach na podstawie tabeli cen oraz tabeli rabatów. Rabaty
są wspólne dla produktów i naliczane są w kolejne dni.

In [12]:
ceny_produktow = np.array([
# produkty
[100, 70, 140], # dzień 1
[120, 80, 150], # dzień 2
[120, 80, 130], # dzień 3
[130, 70, 120], # dzień 4
])
# dzień: 1 2 3 4
rabaty = np.array([0, 10, 20, 30])
prices = ceny_produktow - rabaty.reshape(-1, 1)
print(prices)

[[100  70 140]
 [110  70 140]
 [100  60 110]
 [100  40  90]]


### Ćwiczenie 35: Mapa wartości
Utwórz mapę wartości o rozmiarze 1000x1000 tak, aby w lewym górnym rogu była wartość 0 a prawym dolnym
wartość 1. wartości pomiędzy powinny rosnąć liniowo, tak jak ma to miejsce na przykład w tablicy poniżej:

In [39]:
x = np.linspace(0,1,1001).reshape(1,-1)
y = np.linspace(0,1,1001).reshape(-1, 1)
mapa = x * y
print(mapa[-5:, -5:])

[[0.992016 0.993012 0.994008 0.995004 0.996   ]
 [0.993012 0.994009 0.995006 0.996003 0.997   ]
 [0.994008 0.995006 0.996004 0.997002 0.998   ]
 [0.995004 0.996003 0.997002 0.998001 0.999   ]
 [0.996    0.997    0.998    0.999    1.      ]]


## 1.6. Własne funkcje uniwersalne

### Ćwiczenie 36: Oceny z testów
Napisz funkcję uniwersalną, która przyjmuje tablicę wyników (0-100) i zwraca oceny według skali:
• poniżej 50: „2”
• 5069: „3”
• 7084: „4”
• 85100: „5”
Następnie zastosuj tę funkcję do tablicy 2D reprezentującej wyniki wielu uczniów z różnych testów:

In [50]:
wyniki = np.array([
# test:
# 1 2 3 4
[45, 67, 89, 92], # uczeń 1
[78, 83, 95, 89], # uczeń 2
[49, 65, 75, 83] # uczeń 3
])
def ocena(x):
    if x < 50:
        return 2
    elif x < 70:
        return 3
    elif x <85:
        return 4
    else:
        return 5

ocena_v = np.vectorize(ocena)

print(ocena_v(wyniki))

[[2 3 5 5]
 [4 4 5 5]
 [2 3 4 4]]


### Ćwiczenie 37: Zmiana wartości
Napisz funkcję uniwersalną, która przyjmuje tablicę danych opisujących czas trwania eksperymentu i dokonuje
konwersji z formatu „HH:MM” na sekundy. Przykładowa tablica danych wygląda następująco:

In [61]:
experiments_duration = np.array(["01:20","03:15","02:45", "01:23", "02:24", "01:47"])

def convert(hour):
    h, m = hour.split(':')
    return int(h) * 3600 + int(m) * 60

convert_v = np.vectorize(convert)
print(convert_v(experiments_duration))

[ 4800 11700  9900  4980  8640  6420]


### Ćwiczenie 38: Tabela BMI
Napisz funkcję, która przyjmuje dwa argumenty: masę wyrażoną w kilogramach oraz wzrost w centymetrach i
zwraca wartości:

In [64]:
def bmi_calc(mass, height):
    if height == 0: return np.nan
    bmi = mass / (height/100)**2
    if bmi >= 30: return 2 # 2.0 - patrz opis poniżej
    elif bmi >= 25: return 1 # 1.0
    elif bmi >= 18.5: return 0 # 0.0
    else: return -1 # -1.0
bmi_calc_vec = np.vectorize(bmi_calc)

mass = np.array([90, 80, 94, 107])
height = np.array([172, 189, 0, 164])

print(bmi_calc_vec(mass, height))

ValueError: cannot convert float NaN to integer

## 1.7 Funkcje agregujce i statystyki opisowe

#### 1. Napisz funkcję, która zwraca tablicę o rozmiarze n wypełnioną liczbami całkowitymi z podanego zakresu.
Rozkład wartości powinien być jednostajny.

In [88]:
def tablica_jednostajna(n, min_val, max_val):
    return np.random.randint(min_val, max_val - 1, size = n)

#### 2. Zmodyfikuj funkcję, z poprzedniego zadania,w taki sposób, aby zwracała liczby całkowite spełniające wymogi rozkładu normalnego. 
Liczby powinny być skupione wokół podanej wartości z ustalonym rozrzutem.

In [76]:
def tablica_normalna(n, avg, std):
    arr = np.random.normal(loc = avg, scale= std, size = n)
    return np.round(arr).astype(int)

#### 3. Napisz funkcję, która zwraca tablice o rozmiarze n x m wypełnioną wartościami opisanymi w punkcie 1.

In [79]:
def tablica_jednostajna_nm(n, m, min_wartosc, max_wartosc):
    return tablica_jednostajna(n*m, min_wartosc, max_wartosc).reshape(n, m)

### Ćwiczenie 39: Temperatury
Masz tablicę pomiarów temperatury z 24 godzin:
temperatury = tablica_jednostajna(24, 18, 26)

In [92]:
temps = tablica_jednostajna(24, 18, 26)
print(temps)

[20 18 21 20 19 23 21 18 20 22 20 18 21 22 19 22 18 20 20 18 19 18 20 20]


Napisz program, który:
• znajdzie najwyższą i najniższą temperaturę,
• obliczy średnią temperaturę,
• obliczy różnicę między temperaturą maksymalną a minimalną.
• obliczy liczbę dni ze średnią temperaturą większą niż 22 stopnie,
• obliczy średnią temperaturę dla zbioru temperatur powyżej 22 stopni.

In [97]:
min, max = np.min(temps), np.max(temps)

In [103]:
average = np.mean(temps)
dailies = np.sum(temps > 22)
avg_dail = np.mean(dailies)

### Ćwiczenie 40: Zawody sportowe
Dana jest tablica wyników trzech drużyn w czterech konkurencjach:

In [106]:
wyniki = tablica_jednostajna_nm(3, 4, 0, 10)

In [136]:
wyniki
# Srednia dla kazdej dru
team_avg = np.mean(wyniki,axis=1)
for i, aver in enumerate(team_avg):
    print(f"Srednia druzyny {i+1}: {aver:.2f}")
comp_max = np.max(wyniki, axis=0)
for i, wynik in enumerate(comp_max):
    print(f"Najlepszy wynik w konkurencji {i+1}: {wynik:.2f}")
# Odchylenie standardowe dla każdej drużyny
odchylenia = np.std(wyniki, axis=1)
# Znalezienie indeksu drużyny z najmniejszym odchyleniem
# Funkcja argmin zwraca indeks najmniejszego elementu tablicy
druzyna_minstd_index = np.argmin(odchylenia)
print(f"Najmniejsze odchylenie standardowe ma drużyna {druzyna_minstd_index + 1}")

Srednia druzyny 1: 4.75
Srednia druzyny 2: 4.00
Srednia druzyny 3: 3.00
Najlepszy wynik w konkurencji 1: 7.00
Najlepszy wynik w konkurencji 2: 7.00
Najlepszy wynik w konkurencji 3: 6.00
Najlepszy wynik w konkurencji 4: 7.00
Najmniejsze odchylenie standardowe ma drużyna 3


### Ćwiczenie 41: Analiza sprzedaży
Masz dane sprzedaży z pięciu sklepów za ostatni tydzień:

In [141]:
sprzedaz = tablica_jednostajna_nm(5, 7, 10, 20) * 1000
sprzedaz

array([[12000, 11000, 11000, 10000, 18000, 18000, 15000],
       [12000, 16000, 16000, 11000, 11000, 15000, 10000],
       [13000, 18000, 15000, 12000, 16000, 17000, 11000],
       [13000, 13000, 14000, 14000, 10000, 12000, 17000],
       [17000, 18000, 14000, 17000, 13000, 11000, 12000]])

In [161]:
# Laczna sprzedaz kazdego sklepu
total_sell = np.sum(sprzedaz, axis = 1)
print(f"Lczna sprzedaz sklepów: ", total_sell)
# Dzień z najwyższą łączną sprzedażą we wszystkich sklepach,
day_sale = np.sum(sprzedaz, axis = 0)
day_with_highest_sale = np.argmax(day_sale)
print("day_with_highest_sale ", day_with_highest_sale)
# średnią dzienną sprzedaż dla każdego sklepu.
day_avg = np.mean(sprzedaz, axis = 1)

Lczna sprzedaz sklepów:  [ 95000  91000 102000  93000 102000]
day_with_highest_sale  1


### Ćwiczenie 42: Problemy z ciśnieniem
Masz tablicę z pomiarami ciśnienia krwi pacjentów:

In [166]:
cisnienie = np.array([
# [skurczowe, rozkurczowe]
[120, 80], # pacjent 1
[130, 85], # pacjent 2
[125, 82], # ...
[140, 90],
[135, 88],
[128, 83]
])


In [192]:
# Napisz program, który znajdzie:
# • indeksy pacjentów z ciśnieniem skurczowym powyżej 130
idx = np.where(cisnienie[:,0] > 130)[0]
# Liczbę pacjentów z ciśnieniem rozkurczowym poniżej 85
pat_sum = np.sum(cisnienie[:,1] < 85)
# Średnia wartość ciśnienia dla pacjentów z prawidłowym ciśnieniem (skurczowe <= 130 i rozkurczowe <= 85)
maska = (cisnienie[:,0] <= 130) & (cisnienie[:,1] <= 85)
correct = cisnienie[maska]
avg = np.mean(correct, axis = 0)
print(avg)


[125.75  82.5 ]


### Ćwiczenie 43: Analiza ocen
Masz tablicę wyników procentowych z testu dla grupy studentów:

In [211]:
wyniki = tablica_normalna(100, 65, 30)
# zadbajmy o to aby wyniki studentów miały sens:
wyniki[wyniki < 0] = 0
wyniki[wyniki >100] = 100
wyniki = np.clip(tablica_normalna(100, 65, 30), 0, 100)
#Napisz program który:
#• używając np.where(), przypisze oceny według schematu:
#‣ 90 i więcej: 5.0
#‣ 8089: 4.5
#‣ 7079: 4.0
#‣ 6069: 3.5
#‣ 5059: 3.0
#‣ poniżej 50: 2.0
#• wyświetli pierwotny wynik obok oceny dla każdego studenta,
#• policzy, ilu studentów otrzymało każdą z ocen.
# Przypisanie ocen używając np.where()
oceny = np.where(wyniki >= 90, 5.0,
np.where(wyniki >= 80, 4.5,
np.where(wyniki >= 70, 4.0,
np.where(wyniki >= 60, 3.5,
np.where(wyniki >= 50, 3.0, 2.0)))))
for wynik, ocena in zip(wyniki, oceny):
    print(f"Wynik {wynik:.1f}% -> ocena {ocena}")

# Policzenie liczby studentów z każdą oceną
oceny_wartosci = [2.0, 3.0, 3.5, 4.0, 4.5, 5.0]
for ocena in oceny_wartosci:
    liczba_studentow = np.sum(oceny == ocena)
print(f"Studenci z ocena {ocena}: {liczba_studentow}")

Wynik 82.0% -> ocena 4.5
Wynik 77.0% -> ocena 4.0
Wynik 100.0% -> ocena 5.0
Wynik 31.0% -> ocena 2.0
Wynik 70.0% -> ocena 4.0
Wynik 83.0% -> ocena 4.5
Wynik 100.0% -> ocena 5.0
Wynik 22.0% -> ocena 2.0
Wynik 100.0% -> ocena 5.0
Wynik 73.0% -> ocena 4.0
Wynik 50.0% -> ocena 3.0
Wynik 85.0% -> ocena 4.5
Wynik 99.0% -> ocena 5.0
Wynik 38.0% -> ocena 2.0
Wynik 100.0% -> ocena 5.0
Wynik 63.0% -> ocena 3.5
Wynik 79.0% -> ocena 4.0
Wynik 39.0% -> ocena 2.0
Wynik 70.0% -> ocena 4.0
Wynik 88.0% -> ocena 4.5
Wynik 56.0% -> ocena 3.0
Wynik 36.0% -> ocena 2.0
Wynik 91.0% -> ocena 5.0
Wynik 47.0% -> ocena 2.0
Wynik 74.0% -> ocena 4.0
Wynik 89.0% -> ocena 4.5
Wynik 100.0% -> ocena 5.0
Wynik 96.0% -> ocena 5.0
Wynik 52.0% -> ocena 3.0
Wynik 69.0% -> ocena 3.5
Wynik 28.0% -> ocena 2.0
Wynik 70.0% -> ocena 4.0
Wynik 94.0% -> ocena 5.0
Wynik 60.0% -> ocena 3.5
Wynik 69.0% -> ocena 3.5
Wynik 49.0% -> ocena 2.0
Wynik 45.0% -> ocena 2.0
Wynik 82.0% -> ocena 4.5
Wynik 81.0% -> ocena 4.5
Wynik 51.0% -> ocena

## 1.8. Łączenie i dzielenie tablic

### Ćwiczenie 44: Jak działa stack?
Mamy trzy tablice:

In [224]:
tab_1 = np.ones((4, 4))
tab_2 = tab_1 * 2
tab_3 = tab_1 * 3
stack_1 = np.stack((tab_1, tab_2, tab_3), axis = 2)
stack_2 = np.stack((tab_1, tab_2, tab_3), axis=0)
print(stack_1[0,0])
print(stack_2[0,0])


[1. 2. 3.]
[1. 1. 1. 1.]


### Ćwiczenie 45: np.concatenate()
Wykorzystując tablice tab_1 i tab_2 z poprzedniego zadania utwórz tablicę pokazaną poniżej:

In [247]:
first =  np.concatenate((tab_1, tab_2), axis = 1)
second = np.concatenate((tab_2, tab_1), axis = 1)
res = np.concatenate((first,second), axis= 0)
res

array([[1., 1., 1., 1., 2., 2., 2., 2.],
       [1., 1., 1., 1., 2., 2., 2., 2.],
       [1., 1., 1., 1., 2., 2., 2., 2.],
       [1., 1., 1., 1., 2., 2., 2., 2.],
       [2., 2., 2., 2., 1., 1., 1., 1.],
       [2., 2., 2., 2., 1., 1., 1., 1.],
       [2., 2., 2., 2., 1., 1., 1., 1.],
       [2., 2., 2., 2., 1., 1., 1., 1.]])

### Ćwiczenie 46: Inny sposób
Utwórz tablicę opisana w poprzednim zadaniu wykorzystując zaawansowane metody selekcji wycinków.

In [266]:
n = 8
tab = np.ones((n, n))
tab[(n // 2):n, 0:(n // 2)] = tab[(n // 2):n, 0:(n // 2)] * 2
tab[0: n//2,(n // 2):n] = tab[0: n//2,(n // 2):n] * 2
tab

array([[1., 1., 1., 1., 2., 2., 2., 2.],
       [1., 1., 1., 1., 2., 2., 2., 2.],
       [1., 1., 1., 1., 2., 2., 2., 2.],
       [1., 1., 1., 1., 2., 2., 2., 2.],
       [2., 2., 2., 2., 1., 1., 1., 1.],
       [2., 2., 2., 2., 1., 1., 1., 1.],
       [2., 2., 2., 2., 1., 1., 1., 1.],
       [2., 2., 2., 2., 1., 1., 1., 1.]])

### Ćwiczenie 47: Uśrednianie pikseli
Tablice zdefiniowane poniżej opisują trzy obrazy o rozmiarze 16x16 pikseli w skali szarości o wartościach z
przedziału od 0 do 1. Dokonaj „złożenia” tych obrazów w jeden, uśredniając wartości dla każdego piksela.

In [269]:
n = 16

In [285]:
p1 = np.random.rand(n**2).reshape(n,n)
p2 = np.random.rand(n**2).reshape(n,n)
p3 = np.random.rand(n**2).reshape(n,n)

p = np.stack((p1,p2,p3), axis = 0)
mean_p = np.mean(p, axis = 0)
p[:,0 ,0]


array([0.44705453, 0.82010664, 0.49524765])

### Ćwiczenie 48: Nieśmiertelne zadanie z BMI

In [296]:
wiek = tablica_jednostajna_nm(5, 1, 20, 80) # lata
waga = tablica_jednostajna_nm(5, 1, 50, 100) # kilogramy
wzrost = tablica_jednostajna_nm(5, 1, 150, 190) # centymetry
people = np.hstack((wiek, waga, wzrost))
hm = wzrost / 180
bmi = waga / hm

ppl_bmi = np.hstack((people, bmi))
ppl_bmi

array([[ 48.        ,  71.        , 182.        ,  70.21978022],
       [ 41.        ,  65.        , 185.        ,  63.24324324],
       [ 58.        ,  87.        , 163.        ,  96.07361963],
       [ 29.        ,  59.        , 159.        ,  66.79245283],
       [ 73.        ,  55.        , 182.        ,  54.3956044 ]])

### Ćwiczenie 49: Roczne wyniki sprzedaży
Masz tablicę zawierającą wyniki sprzedaży z całego roku (365 dni):

In [321]:
sprzedaz = np.random.uniform(100, 200, size=365)
months = np.array_split(sprzedaz, 12)
avg = np.mean(months, axis= 1 )


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (12,) + inhomogeneous part.

## 1.9. Rozszerzanie i powtarzanie tablic

### Ćwiczenie 50: Szachownica
Utwórz wzór szachownicy 2x2:

In [333]:
wzor = np.array([[1, 0], [0 ,1]])
res = np.tile(wzor,(4,4))
suma_lg = np.sum(res[0:2, 0:2])

### Ćwiczenie 51: Dane pomiarowe
Mamy jednowymiarową tablicę zawierającą dane:

In [336]:
dane = np.array([56, 75, 69, 55, 49, 59, 77, 82])

Napisz program, który, doda kolejny wymiar do tablicy, utworzy tablicę z trzema kolejnymi danymi dla każdej
wartości używając np.repeat() i doda losowy szum ±2 do powtórzonych danych.

In [351]:
dane_2d = dane[:, np.newaxis]
dane_rep  = np.repeat(dane_2d, 3, axis = 1)

szum = np.random.uniform(-2, 2, dane_rep.shape)
print(szum)
dane_szum = dane_rep + szum
print(dane_szum)

[[-0.33580041  1.48058008  0.73473582]
 [-0.63635362  0.26248264  1.4251021 ]
 [-0.50614698 -1.171712   -1.05920962]
 [ 1.18031503  0.98090675 -0.18541197]
 [ 1.91730268 -1.71798363  0.60755818]
 [-1.52663416 -1.99785952  0.13788126]
 [ 1.88114638  0.19379233  1.50084819]
 [-0.1850509   1.84060615  1.93772986]]
[[55.66419959 57.48058008 56.73473582]
 [74.36364638 75.26248264 76.4251021 ]
 [68.49385302 67.828288   67.94079038]
 [56.18031503 55.98090675 54.81458803]
 [50.91730268 47.28201637 49.60755818]
 [57.47336584 57.00214048 59.13788126]
 [78.88114638 77.19379233 78.50084819]
 [81.8149491  83.84060615 83.93772986]]


### Ćwiczenie 52: Siatka punktów
Mając tablicę wartości x:

In [354]:
x = np.array([1, 2, 3, 4, 5])

Napisz program, który utworzy siatkę 5x5 wartości, gdzie każdy wiersz to wartości x, utworzy drugą siatkę 5x5,
gdzie każda kolumna to wartości x. Następnie, używając tych siatek, oblicz wartości funkcji 𝑓(𝑥, 𝑦) = 𝑥 ⋅ 𝑦 dla
wszystkich punktów siatki.

In [401]:
mesh_x = np.tile(x, (5, 1))
mesh_y = np.repeat(x[:,np.newaxis],5 ,axis =1)
func = mesh_x * mesh_y



[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]


### Ćwiczenie 53: Obrazy dla modelu ML
Mamy zestaw obrazów w skali szarości, zdefiniowanych następująco:

In [404]:
obrazy = np.random.rand(10, 32, 32) # 10 obrazów 32x32 piksele

Napisz program, który doda wymiar kanału koloru do każdego obrazu (zmieniając kształt na (10,28,28,1)), stworzy
kopię każdego obrazu z obrotem o 90 stopni i połączy oryginalne i obrócone obrazy w jeden zestaw danych
(łączenie względem osi 0).

In [413]:
obraz_4d = obrazy[:,:,:,np.newaxis]
rotated = np.rot90(obraz_4d, k=1, axes=(1,2))