In [3]:
import numpy as np
import matplotlib as plt

## Slicing

In [27]:
# x[begin:end:step]

# Jednowymiarowe tablice
x1 = np.array([3, 4, 0, 3, 8 ,6])
print(x1[:3])
print(x1[3:])
print(x1[1:3])
print(x1[[1,4]])
print(x1[1::2])

[3 4 0]
[3 8 6]
[4 0]
[4 8]
[4 3 6]


In [29]:
# Wielowymiarowe tablice

In [49]:
x2 = np.array([[12, 1, 3, 7],[4, 0, 2, 3], [0, 0, 6, 9]])
x2[:2, :3]
x2[:3, ::2]
x2[::-1, ::-1]
x2[:,0]
x2[0,:]

array([12,  1,  3,  7])

In [ ]:
# Podtablice jako widoki bez kopiowania

In [53]:
x2_sub = x2[:2,:2]
x2_sub

array([[12,  1],
       [ 4,  0]])

In [ ]:
# Kopiowanie tablicy

In [57]:
x2_sub_copy = x2[:2,:2].copy()
x2_sub_copy

array([[12,  1],
       [ 4,  0]])

## Zmiana kształtu

In [62]:
grid = np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
x  = np.array([1, 2, 3])


In [74]:
# Wektor wierszowy
x[np.newaxis,:]

array([[1, 2, 3]])

In [76]:
# Wektor kolumnowy
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

## Konkatenacja

In [89]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [91]:
grid = np.array([[1, 2, 3],[4, 5, 6]])

In [97]:
# Konkatencja wzdłuż pierwszej osi ,axis 0
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [99]:
np.concatenate([grid,grid], axis  = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [101]:
# łczenie tablic w pionie (Dokładamy wiersze czyli V stack działa w osi 0)
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [109]:
# łaczenie w poziomie
y =np.array([[99],[99]])
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [111]:
# Dzielenie tablic
grid = np.arange(16).reshape(4,4)

In [113]:
upper, lower = np.vsplit(grid, [2])